Try porting vehicle routing to use list variable
apache/incubator-kie-optaplanner-quickstarts pull request #280
Opened 2022-02-01 16:37 UTC by Christopher-Chianelli

### JIRA

### Referenced pull requests

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add the label `run_fdb`
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] tests</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaplanner-quickstarts] native</b>
</details>

2022-02-02 15:25 UTC, yurloc commented
I get an error after a few seconds of solving:

```
Error id 9e4b0606-35bd-402f-9340-097dc7464cbf-1, org.jboss.resteasy.spi.UnhandledException: com.fasterxml.jackson.databind.JsonMappingException: Index 12 out of bounds for length 12 (through reference chain: org.acme.vehiclerouting.rest.Status["solution"]-&gt;org.acme.vehiclerouting.domain.VehicleRoutingSolution["vehicleList"]-&gt;java.util.ArrayList[3]-&gt;org.acme.vehiclerouting.domain.Vehicle["customerList"]-&gt;java.util.ArrayList[12])
org.jboss.resteasy.spi.UnhandledException: com.fasterxml.jackson.databind.JsonMappingException: Index 12 out of bounds for length 12 (through reference chain: org.acme.vehiclerouting.rest.Status["solution"]-&gt;org.acme.vehiclerouting.domain.VehicleRoutingSolution["vehicleList"]-&gt;java.util.ArrayList[3]-&gt;org.acme.vehiclerouting.domain.Vehicle["customerList"]-&gt;java.util.ArrayList[12])
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:368)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:614)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Index 12 out of bounds for length 12 (through reference chain: org.acme.vehiclerouting.rest.Status["solution"]-&gt;org.acme.vehiclerouting.domain.VehicleRoutingSolution["vehicleList"]-&gt;java.util.ArrayList[3]-&gt;org.acme.vehiclerouting.domain.Vehicle["customerList"]-&gt;java.util.ArrayList[12])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:363)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:338)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:123)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1518)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1007)
	at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.writeTo(ResteasyJackson2Provider.java:345)
	at org.jboss.resteasy.core.messagebody.AsyncBufferedMessageBodyWriter.asyncWriteTo(AsyncBufferedMessageBodyWriter.java:24)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:87)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.asyncProceed(AbstractWriterInterceptorContext.java:203)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getStarted(AbstractWriterInterceptorContext.java:166)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$getStarted$0(ServerWriterInterceptorContext.java:73)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.aroundWriteTo(ServerWriterInterceptorContext.java:93)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.getStarted(ServerWriterInterceptorContext.java:73)
	at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:163)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404)
	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:594)
	... 16 more
Caused by: java.lang.IndexOutOfBoundsException: Index 12 out of bounds for length 12
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:103)
	... 48 more
```

2022-02-02 15:28 UTC, Christopher-Chianelli commented
IIRC, that error does not stop solving, and the web app continues updating fine. I think it caused by the list being modified when serializing it.

2022-02-02 16:39 UTC, yurloc requested changes
Code looks good but the app is broken. Throws IndexOutOfBounds and ConcurrentModification exceptions while solving.

2022-02-02 16:39 UTC, yurloc commented on use-cases/vehicle-routing/src/main/java/org/acme/vehiclerouting/domain/VehicleRoutingSolution.java
>      @ValueRangeProvider(id = "vehicleRange")
This annotation is now redundant.

2022-02-02 16:39 UTC, yurloc commented on use-cases/vehicle-routing/src/main/java/org/acme/vehiclerouting/solver/VehicleRoutingConstraintProvider.java
>  import org.acme.vehiclerouting.domain.Customer;
Unused imports.

2022-02-02 16:39 UTC, yurloc commented on use-cases/vehicle-routing/src/main/java/org/acme/vehiclerouting/domain/Vehicle.java
> +            totalDistance += customer.getLocation().getDistanceTo(lastLocation);
Wrong order. If the distances were asymmetric, this would result in distance traveled in reverse order.

2022-02-02 16:39 UTC, yurloc commented on use-cases/vehicle-routing/src/main/java/org/acme/vehiclerouting/domain/Customer.java
> +//@PlanningEntity
Surprisingly, no shadow variables are necessary with the current approach. If it works then please remove the commented out code (and fix imports) and the unused `vehicle` field.

2022-02-02 19:26 UTC, Christopher-Chianelli commented
The error was caused by https://issues.redhat.com/browse/PLANNER-2661, which will be fixed by https://github.com/kiegroup/optaplanner/pull/1823

2022-02-04 12:05 UTC, yurloc approved these changes
A few obsolete `@JsonIgnore`s, otherwise looks good. Great work and thanks for finding and fixing the cloning bug!

2022-02-04 12:05 UTC, yurloc commented on use-cases/vehicle-routing/src/main/java/org/acme/vehiclerouting/domain/Customer.java
>  @JsonIgnoreProperties({ "previousStandstill", "nextCustomer" })
Obsolete.

2022-02-04 12:05 UTC, yurloc commented on use-cases/vehicle-routing/src/main/java/org/acme/vehiclerouting/domain/Vehicle.java
>  @JsonIgnoreProperties({ "nextCustomer" })
Obsolete.

2022-02-04 12:05 UTC, yurloc commented on use-cases/vehicle-routing/src/main/java/org/acme/vehiclerouting/domain/Vehicle.java
> +            totalDistance += lastLocation.getDistanceTo(depot.getLocation());
Tip: the distance algorithm could be aligned with the route algorithm:
1. If customerList is empty, then return 0.
2. Customer loop.
3. At the and you can skip the "if lastLocation != depot" because you know the `lastLocation` is a customer.

Pros:
* consistency with the route algorithm
* easier to read (subjectively)

2022-02-04 21:34 UTC, merged