[BXMSPROD-1881] dependabot for release and blue branches
apache/incubator-kie-optaplanner-quickstarts pull request #457
Opened 2022-11-23 09:26 UTC by Ginxo

2022-11-23 09:32 UTC, mareknovotny approved these changes

2022-11-23 09:42 UTC, rsynek requested changes
First of all, please open the PR against the `development` branch. The `stable` branch is rather read-only.

As for which branches we cover by `dependabot`, why there is not the `8.29.x`?

2022-11-23 09:42 UTC, rsynek commented on .github/dependabot.yml
> +  target-branch: "main"
This should have been probably `development`, as there is no `main` branch.

2022-11-23 09:42 UTC, rsynek commented on .github/dependabot.yml
> +    prefix: "[bot][main]"
ditto

2022-11-23 09:54 UTC, Ginxo commented
> First of all, please open the PR against the `development` branch. The `stable` branch is rather read-only.
> 
> As for which branches we cover by `dependabot`, why there is not the `8.29.x`?

@rsynek according to documentation dependabot.yml should be placed on default branch from repository, so...
8.29.x branch added

2022-11-23 09:58 UTC, rsynek commented
> > First of all, please open the PR against the `development` branch. The `stable` branch is rather read-only.
> > As for which branches we cover by `dependabot`, why there is not the `8.29.x`?
> 
> @rsynek according to documentation dependabot.yml should be placed on default branch from repository, so... 8.29.x branch added

That may well be the case, but every release we reset the `stable` branch to the current release branch. In other words, any changes you make to the `stable` branch directly are only temporary.

2022-11-24 08:59 UTC, radtriste commented
> > > First of all, please open the PR against the `development` branch. The `stable` branch is rather read-only.
> > > As for which branches we cover by `dependabot`, why there is not the `8.29.x`?
> > 
> > 
> > @rsynek according to documentation dependabot.yml should be placed on default branch from repository, so... 8.29.x branch added
> 
> That may well be the case, but every release we reset the `stable` branch to the current release branch. In other words, any changes you make to the `stable` branch directly are only temporary.

I agree with @rsynek, we should set it against `development` and not `stable`.
`stable` will be anyway updated in the next release, so no point to update there anything ...

2022-11-24 13:49 UTC, mareknovotny commented
you do not merge development to stable branch? @rsynek @radtriste

2022-11-24 13:56 UTC, radtriste commented
nope, we recreate the branch directly from the tag

2022-11-25 10:30 UTC, Ginxo commented
closed in favor of https://github.com/kiegroup/optaplanner-quickstarts/pull/459

2022-11-25 10:30 UTC, closed without merging