[BXMSPROD-2016] Updating references to the new kie-ci actions folder.
apache/incubator-kie-optaplanner-quickstarts pull request #562
Opened 2023-05-03 09:32 UTC by bacciotti

2023-05-18 08:41 UTC, lampajr commented
@bacciotti please apply these changes to the `development` branch, as this `stable` branch is auto-generated from time to time

2023-05-18 08:58 UTC, Ginxo requested changes
all changes should be done over development branch, they will be propagated to stable once merged

2023-05-22 11:24 UTC, kie-ci3 commented
**(tests) - optaplanner-quickstarts job** `#14` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dfull 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/optaplanner/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/optaplanner-quickstarts -u https://github.com/kiegroup/optaplanner-quickstarts/pull/562 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner-9.x/job/9.x/job/pullrequest/job/optaplanner-quickstarts.tests.optaplanner-quickstarts/14/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
GitHub pull request #562 of commit 0431635b706827c5b95c94137030da5b2d65704f, has merge conflicts.<br/>Setting status of 0431635b706827c5b95c94137030da5b2d65704f to PENDING with url https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner-9.x/job/9.x/job/pullrequest/job/optaplanner-quickstarts.tests.optaplanner-quickstarts/14/display/redirect and message: 'Build started.'<br/>Using context: (build) optaplanner-quickstarts<br/>Checking out git https://github.com/kiegroup/kogito-pipelines.git into /var/jenkins_home/jobs/KIE/jobs/optaplanner-9.x/jobs/9.x/jobs/pullrequest/jobs/optaplanner-quickstarts.tests.optaplanner-quickstarts/workspace@script/ee10b829cbd0ac763d0be6f0356db3418b2d4469e9daa1842e842313521cde92 to read .ci/jenkins/Jenkinsfile.buildchain<br/>The recommended git tool is: NONE<br/>using credential kie-ci<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/optaplanner-9.x/jobs/9.x/jobs/pullrequest/jobs/optaplanner-quickstarts.tests.optaplanner-quickstarts/workspace@script/ee10b829cbd0ac763d0be6f0356db3418b2d4469e9daa1842e842313521cde92/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/>Cleaning workspace<br/> > git rev-parse --verify HEAD # timeout=10<br/>Resetting working tree<br/> > git reset --hard # timeout=10<br/> > git clean -fdx # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/>Checking out Revision e91f6eaba901315d56073188c7a79bb549c1e594 (origin/main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f e91f6eaba901315d56073188c7a79bb549c1e594 # timeout=10<br/>Commit message: "Add release branch 1.39.x after cut-off"<br/>First time build. Skipping changelog.<br/>Loading library jenkins-pipeline-shared-libraries@main<br/>Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh2288530061141871714.key<br/>Verifying host key using manually-configured host key entries<br/> > git ls-remote -h -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision 0510a173ee21200297790c8e7a18835f47d32d17<br/>Selected Git installation does not exist. Using Default<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/optaplanner-9.x/jobs/9.x/jobs/pullrequest/jobs/optaplanner-quickstarts.tests.optaplanner-quickstarts/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/jenkins_home/jobs/KIE/jobs/optaplanner-9.x/jobs/9.x/jobs/pullrequest/jobs/optaplanner-quickstarts.tests.optaplanner-quickstarts/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh15904911232074598786.key<br/>Verifying host key using manually-configured host key entries<br/> > git fetch --no-tags --force --progress -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 0510a173ee21200297790c8e7a18835f47d32d17 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 0510a173ee21200297790c8e7a18835f47d32d17 # timeout=10<br/>Commit message: "KOGITO-8455: create release with release notes (#273)"<br/> > git rev-list --no-walk 1c38a89adccfe24f4cc72e5b4f91fc15465a1c45 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Running on rhos-01-kie-psi-rhel7-xlarge-9465 in /home/jenkins/workspace/KIE/optaplanner-9.x/9.x/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci<br/>Cloning the remote Git repository<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/optaplanner-9.x/9.x/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.39.2'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Avoid second fetch<br/>Checking out Revision e91f6eaba901315d56073188c7a79bb549c1e594 (origin/main)<br/>Commit message: "Add release branch 1.39.x after cut-off"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2023-05-22T11:24:18.893Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f e91f6eaba901315d56073188c7a79bb549c1e594 # timeout=10<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-0 [...]

2023-05-23 10:22 UTC, bacciotti commented
Closing this PR as a new one was created with the suggestions and without conflicts.

2023-05-23 10:22 UTC, closed without merging

2023-05-23 10:26 UTC, kie-ci3 commented
**(tests) - optaplanner-quickstarts job** `#17` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dfull 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/optaplanner/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/optaplanner-quickstarts -u https://github.com/kiegroup/optaplanner-quickstarts/pull/562 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/optaplanner-9.x/job/9.x/job/pullrequest/job/optaplanner-quickstarts.tests.optaplanner-quickstarts/17/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T10:25:54.311Z] [INFO] ---------< org.optaplanner:optaplanner-distribution-internal >----------<br/>[2023-05-23T10:25:54.311Z] [INFO] Building OptaPlanner distribution internal 9.40.0-SNAPSHOT       [49/49]<br/>[2023-05-23T10:25:54.311Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2023-05-23T10:25:54.311Z] [INFO] <br/>[2023-05-23T10:25:54.311Z] [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:54.311Z] [INFO] <br/>[2023-05-23T10:25:54.311Z] [INFO] --- formatter-maven-plugin:2.22.0:validate (default) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:54.311Z] [INFO] Formatting is skipped<br/>[2023-05-23T10:25:54.311Z] [INFO] <br/>[2023-05-23T10:25:54.311Z] [INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-no-logback-test-in-main) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:54.311Z] [INFO] Skipping Rule Enforcement.<br/>[2023-05-23T10:25:54.311Z] [INFO] <br/>[2023-05-23T10:25:54.311Z] [INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (no-managed-deps) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:54.311Z] [INFO] Skipping Rule Enforcement.<br/>[2023-05-23T10:25:54.311Z] [INFO] <br/>[2023-05-23T10:25:54.311Z] [INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (ban-forbidden-dependencies) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:54.311Z] [INFO] Skipping Rule Enforcement.<br/>[2023-05-23T10:25:54.311Z] [INFO] <br/>[2023-05-23T10:25:54.311Z] [INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (no-duplicate-declared-dependencies) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:54.311Z] [INFO] Skipping Rule Enforcement.<br/>[2023-05-23T10:25:54.311Z] [INFO] <br/>[2023-05-23T10:25:54.311Z] [INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-java-version) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:54.311Z] [INFO] Skipping Rule Enforcement.<br/>[2023-05-23T10:25:54.311Z] [INFO] <br/>[2023-05-23T10:25:54.311Z] [INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-maven-version) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:54.311Z] [INFO] Skipping Rule Enforcement.<br/>[2023-05-23T10:25:54.311Z] [INFO] <br/>[2023-05-23T10:25:54.311Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:54.311Z] [INFO] <br/>[2023-05-23T10:25:54.311Z] [INFO] --- impsort-maven-plugin:1.8.0:check (default) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:54.312Z] [INFO] Skipping execution of impsort-maven-plugin<br/>[2023-05-23T10:25:54.312Z] [INFO] <br/>[2023-05-23T10:25:54.312Z] [INFO] --- maven-javadoc-plugin:3.5.0:jar (build-javadoc-jar) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:54.312Z] [INFO] Not executing Javadoc as the project is not a Java classpath-capable package<br/>[2023-05-23T10:25:54.312Z] [INFO] <br/>[2023-05-23T10:25:54.312Z] [INFO] --- maven-source-plugin:3.1.0:jar-no-fork (attach-sources) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:54.312Z] [INFO] <br/>[2023-05-23T10:25:54.312Z] [INFO] --- maven-assembly-plugin:3.4.2:single (default) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:54.312Z] [INFO] Reading assembly descriptor: src/main/assembly/assembly-optaplanner.xml<br/>[2023-05-23T10:25:55.233Z] [INFO] Building zip: /home/jenkins/workspace/KIE/optaplanner-9.x/9.x/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts/bc/kiegroup_optaplanner/build/optaplanner-distribution-internal/target/optaplanner-distribution-internal-9.40.0-SNAPSHOT.zip<br/>[2023-05-23T10:25:58.580Z] [INFO] <br/>[2023-05-23T10:25:58.580Z] [INFO] --- maven-dependency-plugin:3.5.0:analyze-only (analyze-only) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:58.580Z] [INFO] Skipping pom project<br/>[2023-05-23T10:25:58.580Z] [INFO] <br/>[2023-05-23T10:25:58.580Z] [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ optaplanner-distribution-internal ---<br/>[2023-05-23T10:25:58.580Z] [INFO] Installing /home/jenkins/workspace/KIE/optaplanner-9.x/9.x/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts/bc/kiegroup_optaplanner/build/optaplanner-distribution-internal/pom.xml to /home/jenkins/.m2/repository/org/optaplanner/optaplanner-distribution-internal/9.40.0-SNAPSHOT/optaplanner-distribution-internal-9.40.0-SNAPSHOT.pom<br/>[2023-05-23T10:25:58.580Z] [INFO] Installing /home/jenkins/workspace/KIE/optaplanner-9.x/9.x/pullrequest/optaplanner-quickstarts.tests.optaplanner-quickstarts/bc/kiegroup_optaplanner/build/optaplanner-distribution-internal/target/optaplanner-distribution-internal-9.40.0-SNAPSHOT.zip to /home/jenkins/.m2/repository/org/optaplanner/optaplanner-distribution-internal/9.40.0-SNAPSHOT/optaplanner-distribution-internal-9.40.0-SNAPSHOT.zip<br/>[2023-05-23T10:25:58.580Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-23T10:25:58.580Z] [INFO] Reactor Summary for OptaPlanner multiproject parent 9.40.0-SNAPSHOT:<br/>[2023-05-23T10:25:58.580Z] [INFO] <br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner multiproject parent .................... SUCCESS [  0.431 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner BOM (Bill Of Materials) ................ SUCCESS [  0.009 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner IDE Configuration ...................... SUCCESS [  0.381 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner build parent ........................... SUCCESS [  1.880 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner core parent ............................ SUCCESS [  0.015 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner core implementation .................... SUCCESS [ 25.673 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner constraints: Constraint streams (Common) SUCCESS [  4.188 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner constraints: Constraint streams (Drools) SUCCESS [  3.965 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner constraints: DRL (Deprecated) .......... SUCCESS [  2.552 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner constraints: Constraint streams (Bavet)  SUCCESS [  4.709 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner core ................................... SUCCESS [  0.033 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner persistence ............................ SUCCESS [  0.012 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner persistence common ..................... SUCCESS [  1.164 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner persistence XStream (Deprecated) ....... SUCCESS [  1.708 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner persistence JAXB ....................... SUCCESS [  1.660 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner persistence Jackson .................... SUCCESS [  1.902 s]<br/>[2023-05-23T10:25:58.580Z] [INFO] OptaPlanner persistence JPA ........................ SUCCESS [  2.151 s]<br/>[2023-05-23T10:25:58.5 [...]